# Generated by Django 4.2.11 on 2025-05-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', 'add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='calc_total_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_item_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionjob',
            name='prod_status_idx',
        ),
    ]
