# Generated by Django 4.2.11 on 2025-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0002_department_location'),
        ('rumah_akrilik_app', 'XXXX_create_department_table'),
    ]

    operations = [
    ]
