# Generated by Django 4.2.11 on 2025-05-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0003_merge_20250515_2338'),
    ]

    operations = [
    ]
