# Generated by Django 4.2.11 on 2025-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0003_remove_role_permissions_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='biaya_pasang',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='biaya_survey',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='sumber_order',
            field=models.CharField(blank=True, help_text='Contoh: Iklan FB, Kunjungan, Tokopedia, Reseller A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipe_karyawan',
            field=models.CharField(choices=[('tetap', 'Karyawan Tetap'), ('freelance', 'Freelance'), ('magang', 'Magang'), ('pkl', 'PKL'), ('trainee', 'Trainee')], default='tetap', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('credit', 'Credit'), ('partial', 'Partial Payment'), ('cod', 'COD'), ('cod_sebagian', 'COD Sebagian'), ('transfer_sebagian', 'Transfer Sebagian'), ('termin', 'Termin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Simpan spek custom, ukuran, bahan, dll.'),
        ),
    ]
