# Generated by Django 4.2.11 on 2025-04-27 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0004_order_biaya_pasang_order_biaya_survey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Order Counter',
                'verbose_name_plural': 'Daily Order Counters',
            },
        ),
    ]
