# Generated by Django 4.2.11 on 2025-05-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0004_create_department_table'),
        ('rumah_akrilik_app', 'YYYY_add_department_to_userprofile'),
    ]

    operations = [
    ]
