# Generated by Django 4.2.11 on 2025-04-28 16:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumah_akrilik_app', '0005_dailyordercounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produksi',
            options={'ordering': ['order', 'mulai'], 'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_business',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='nama_produk',
            field=models.CharField(default='', help_text='Nama produk saat order ini dibuat', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='Indonesia', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(blank=True, default='Indonesia', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('credit', 'Credit'), ('partial', 'Partial Payment'), ('cod', 'COD'), ('cod_sebagian', 'COD Sebagian'), ('transfer_sebagian', 'Transfer Sebagian'), ('termin', 'Termin')], default='transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='sumber_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('standard', 'Standard Product'), ('custom', 'Custom Product'), ('material', 'Raw Material')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionmaterial',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='realisasikunjunganrr',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='realisasikunjunganrr',
            name='produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunjungan_produk', to='rumah_akrilik_app.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
