# Generated by Django 4.2.11 on 2025-04-28 17:11

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('rumah_akrilik_app', '0006_alter_produksi_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='rumah_akrilik_app_orderitem',
        ),
    ]
