# Generated by Django 4.2.11 on 2025-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0006_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Bahan Baku - Raw Material'), ('support_material', 'Bahan Baku - Support Material'), ('packaging', 'Bahan Baku - Packaging'), ('finished_product', 'Stock Jadi'), ('equipment', 'Peralatan'), ('asset', 'Aset')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='Lembar', max_length=20),
        ),
    ]
