# Generated by Django 4.2.11 on 2025-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0007_fix_orderitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_orders',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total nilai order termasuk biaya tambahan', max_digits=12),
        ),
    ]
