# Generated by Django 4.2.11 on 2025-05-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0008_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='acquisition_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='condition',
            field=models.CharField(default='baik', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_stock',
            field=models.IntegerField(default=1),
        ),
    ]
