# Generated by Django 4.2.11 on 2025-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0008_order_total_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_orders',
        ),
        migrations.AddField(
            model_name='order',
            name='calculated_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total nilai order termasuk biaya tambahan', max_digits=12),
        ),
    ]
