# Generated by Django 4.2.11 on 2025-05-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0002_remove_total_amount_conflict'),
        ('rumah_akrilik_app', '0009_remove_order_total_orders_order_calculated_total'),
    ]

    operations = [
    ]
