# Generated by Django 4.2.11 on 2025-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0009_inventory_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
