# Generated by Django 4.2.11 on 2025-05-18 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumah_akrilik_app', '0010_inventoryrequest_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.IntegerField(default=0)),
                ('adjusted_stock', models.IntegerField(default=0)),
                ('adjustment_quantity', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_adjustments', to='rumah_akrilik_app.inventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
