# Generated by Django 3.2 on 2025-05-02 12:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0010_merge_20250502_1618'),  # Update this to your actual latest migration
    ]

    operations = [
        # No operations - this is a placeholder migration
    ]