# Generated by Django 4.2.11 on 2025-05-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0001_remove_order_order_date_idx_and_more'),
        ('rumah_akrilik_app', '0012_add_performance_indexes'),
    ]

    operations = [
    ]
