# Generated by Django 4.2.11 on 2025-05-07 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumah_akrilik_app', '0013_merge_20250507_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Urutan tahap produksi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Stage',
                'verbose_name_plural': 'Production Stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('rejected', 'Ditolak/Revisi')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Tracking',
                'verbose_name_plural': 'Production Trackings',
                'ordering': ['order', 'stage__order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_total_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_order_idx',
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_productions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_trackings', to='rumah_akrilik_app.order'),
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='rumah_akrilik_app.productionstage'),
        ),
        migrations.AlterUniqueTogether(
            name='productiontracking',
            unique_together={('order', 'stage')},
        ),
    ]
