# Generated by Django 4.2.11 on 2025-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_akrilik_app', '0015_order_alamat_jalan_order_kecamatan_order_kelurahan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='rumah_akrilik_app.role'),
        ),
    ]
