# Generated by Django 4.2.11 on 2025-05-13 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumah_akrilik_app', '0017_notification_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('responsible_user', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('planned', 'Direncanakan'), ('active', 'Aktif'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Plan',
                'verbose_name_plural': 'Marketing Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
